# Generated by Django 5.2 on 2025-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='artikel/'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
