# Generated by Django 5.2 on 2025-05-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_artikel_gambar_artikel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='program/')),
            ],
        ),
    ]
