# Generated by Django 5.2 on 2025-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelolaGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
    ]
